### ISSUE TITLE
An error in metrics.py line 59

### ISSUE THREAD

**Issue by Originlightwkp** [FactoDeepLearning/MultitaskVLFM#2]
100% [......................................................................] 928819451 / 928819451loaded weights - epoch 100
Evaluation on valid:   0%|                                                                                                                                                                        | 0/5794 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "Multitasking/main.py", line 167, in <module>
    main(args)
  File "Multitasking/main.py", line 123, in main
    trainer.evaluate_classification("valid", output=True)
  File "/home/mingbo/anaconda3/envs/wkpfairmot/lib/python3.7/site-packages/MultitaskVLFM-1.0.0-py3.7.egg/Multitasking/trainer.py", line 612, in evaluate_classification
    self.metric_managers[set_name].add_batch_values(metrics)
  File "/home/mingbo/anaconda3/envs/wkpfairmot/lib/python3.7/site-packages/MultitaskVLFM-1.0.0-py3.7.egg/Multitasking/metrics.py", line 39, in add_batch_values
    batch_metrics = self.compute_metrics_from_batch_values(batch_values)
  File "/home/mingbo/anaconda3/envs/wkpfairmot/lib/python3.7/site-packages/MultitaskVLFM-1.0.0-py3.7.egg/Multitasking/metrics.py", line 59, in compute_metrics_from_batch_values
    metrics = metrics | compute_sample_mAP(metrics["preds_attr"], metrics["gt_attr"], metrics['certainty_masks'])
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

what the "|" mean?

**Comment by Originlightwkp** [comment]
i use this ,could it work?
metrics[metric_name] = compute_sample_mAP(metrics["preds_attr"], metrics["gt_attr"],metrics['certainty_masks'])
